### ISSUE TITLE
Configuration for exclusions

### ISSUE THREAD

**Issue by deimosian** [desbma/motd#5]
Hello there, 

I like with is concept and it works fine on regular laptops and desktops... however I would also like to use it on my server, but as is it has 28 cores and 16 drives the output massively overflows the console window. 

Would you be open to the addition of an .ini style configuration file to choose/limit what is dispalyed? Perhaps an option for just package temps, not each core temp and only the root drive, or certain drives, instead of all drives?

Also, a little nitpicky, but the blank lines feel redundant to the dashed section header lines.

**Comment by desbma** [comment]
> however I would also like to use it on my server, but as is it has 28 cores and 16 drives the output massively overflows the console window.

Get a bigger screen and/or a better CPU that does not have a temp probe per core. 
Just kidding of course :wink: 

> Would you be open to the addition of an .ini style configuration file to choose/limit what is dispalyed? Perhaps an option for just package temps, not each core temp and only the root drive, or certain drives, instead of all drives?

Yes, that is a reasonable request, especially since I already have [hardcoded some exclusions](https://github.com/desbma/motd/blob/master/src/temp.rs#L64-L68).

> Also, a little nitpicky, but the blank lines feel redundant to the dashed section header lines.

True, I made it that way because it makes each section more quickly identifiable visually for me, but that is a matter of taste I guess.
You can still get the output you want by running several `motd` instances with each one showing a single section via `-s x`, although it will probably be a few ms slower.

**Comment by desbma** [comment]
Implemented via 7b1dc395b09df6d4e1e37d1f5d392091115dbccd, see https://github.com/desbma/motd#configuration
